### ISSUE TITLE
How to handle secrets in the stack, `io.cozy.account_type` role and usage

### ISSUE THREAD

**Issue by ptbrowne** [cozy/cozy-stack#1127]
I need to pass an API token to a konnector and want this token not to be accessible. For now the API token is in the code but since the konnector code will be public, we want to extract the code.  It seems that the account_type doctype is made to do this (storing secrets and passing them at runtime to a konnector) but maybe I've misunderstood.

I see in https://github.com/cozy/cozy-stack/blob/350c907112157ee966e02584199165b975657585/docs/konnectors_oauth.md that applications should not have access this information. It seems by looking at the stack code. Is it really the case ?

I think the documentation could be improved concerning account_type.

- Is the account_type only for oauth account ?
- What is their role ?
- How are they implemented ?
- How do the konnectors gets the secret information ?

**Comment by nono** [comment]
Currently, the account_type are only for OAuth accounts. We wanted to keep the possibility to extend their role but we didn't implement it (no clear use case until now).

The konnectors don't do the OAuth stuff them-selves, they ask the stack to do it. And the stack puts an access token in the accounts, so that the konnectors can talk to the API. So, the konnectors don't need an access to the secret information, except the access token that is copied to the accounts by the stack.

**Comment by ptbrowne** [comment]
> So, the konnectors don't need an access to the secret information, except the access token that is copied to the accounts by the stack.

The Linxo konnector is not an OAuth token and currently needs the token to access its API. In other words, in this case the konnector needs the secret information. Is it something that this konnector could support ?

**Comment by nono** [comment]
See #1753

**Comment by nono** [comment]
> One solution to use orange api is to use 2-legged authentication, which also needs to use secret data in the connector.

@doubleface if you can you should use the [3-legged authentication](https://developer.orange.com/tech_guide/3-legged-oauth/). It's a more robust version of OAuth.

**Comment by ptbrowne** [comment]
Please reopen if needed, the secrets are now in io.cozy.account_types.
