### ISSUE TITLE
data security concerns

### ISSUE THREAD

**Issue by richardhundt** [cozy/cozy-stack#1395]
Hi, I can't find anything about your security threat model and what you are doing to secure personal data. Is data encrypted at rest? What guarantee is there that cozy.io staff cannot read my data? If your machines are compromised, what limits theft of my data?

I'm pretty sure I'm missing the documentation, and would like some pointers to it. Thanks!

**Comment by clochix** [comment]
Hello @richardhundt,

We have some answers on https://help.cozy.io/

Your most critical data are encrypted on our servers (basically, the passwords used to connect to remote services). Your other data are not encrypted and can be accessed by our server admin. Of course we do our best to secure our servers, and prevent illegal access.

For now, we don't encrypt all your data because processes running on the server side need to access them. For example, creating thumbnails for your pictures requires to access them.
We are working on adding share features to Cozy: soon, you'll be able to share data between several servers. This would be way much harder if data where encrypted.

In the future, we plan to add client-side, end-to-end encryption, so you can choose to encrypt your most valuable data. But we have no precise roadmap.
