### ISSUE TITLE
js in login page broken when LastPass chrome plugin is active

### ISSUE THREAD

**Issue by StudioEtrange** [cozy/cozy-stack#1905]
Since a few days, I am unnable to use my cozy account in your cloud
From 2 different computers, windows and MacOs,
both with chrome

Javascript console error
"An invalid form control with name='two-factor-passcode' is not focusable."

**Comment by nono** [comment]
Hello,

do you have some chrome extensions? If yes, you can try to disable them to see if the issue comes from here. I've heard that a few users have issues with password managers, even if I haven't been able to reproduce this myself.

**Comment by StudioEtrange** [comment]
Hi
You are right !
When i disable my LastPass chrome plugin, and I can log into cozy.

So, it is a problem now between your login page, and LastPass chrome plugin.
I use LastPass on every website to login without a problem.

Could you solve this issue ?
I will not write my cozy password on a paper ;)

**Comment by nono** [comment]
> When i disable my LastPass chrome plugin, and I can log into cozy.

Thanks for the feedback!

> Could you solve this issue ?

We will try, but the issue is more complex than it looks like.

As I understand, browsers doesn't give a very helpful API to the extensions for managing passwords. So, they have to rely on JavaScript with some hard-coded rules. Some password managers have better code than others at this task, but they are all trying to balance the facility to use the password manager on every website, and the impact to do so (performances, cost to maintain the rules). I think that LastPass doesn't know or consider Cozy important enough to have a specific rule for it, and we have more security restrictions that most websites (in technical terms, there is something call Content Security Policy, and ours is quite strict). We don't want to lessen our security restrictions to make LastPass works on our page, but I hope that LastPass will add a rule for websites with similar rules as ours, or that we will find a way to work-around this issue.

> I will not write my cozy password on a paper ;)

Good idea :+1:

By curiosity, why did you choose LastPass instead of an Open-Source solution like [bitwarden](https://bitwarden.com/)?

**Comment by mamyn0va** [comment]
Thanks for your reply, I understand your concerns.
I will have a look at bitwarden.

**Comment by nono** [comment]
@StudioEtrange Hi, do you know if the bug with LastPass was resolved? Or did you migrate to [Cozy Pass](https://cozy.io/en/features/#pass)?

**Comment by StudioEtrange** [comment]
I think it is solved because I can login with LastPass auto fill function

**Comment by nono** [comment]
OK, thanks for the answer
