### ISSUE TITLE
What are all the subdomains used on cozy ?

### ISSUE THREAD

**Issue by dylanbob** [cozy/cozy-stack#785]
Hi
I would like to generate tls certificates using letsencrypt (with certbot).
Where can I find a list of the subdomains used by cozy ?

**Comment by ArchangeGabriel** [comment]
@dylanbob I have the same need, and the answer is that every app will require a specific domain. So they will probably be a base list available at some point (they target September for self-hosting of v3), but then you will have to add certificates on each app installation.

I think they were thinking about tools to automate this, not sure if any progress has been done in this direction.

Basically I think we should use a certificate with the instance domain as CN and then add every required subdomain as SAN. certbot supports adding domain to an existing certificate by renewing it, so that would be my way to do so.

**Comment by nono** [comment]
Each app has its own subdomain, so it depends on which app you have installed. You may start with the most used application: drive, photos, collect and settings.

> I think they were thinking about tools to automate this, not sure if any progress has been done in this direction.

Nothing has been done.

**Comment by dylanbob** [comment]
I understand the issue. I was simply asking for a list of subdomains :)
I couldn't even find a list of apps ? And does every app have a domain on app.cozy.example.com ?

**Comment by clochix** [comment]
Here are the currently available apps: https://github.com/cozy/cozy-stack/blob/d545fbe4bf45eb1ac064205f153991a4b756bb95/pkg/consts/consts.go#L175 (this list is hardcoded until we release the new marketplace).

The domain names depend on your server configuration: https://github.com/cozy/cozy-stack/blob/d545fbe4bf45eb1ac064205f153991a4b756bb95/cozy.example.yaml#L8
So you may have drive.cozy.example.com, photos.cozy.example.com… or cozy-drive.example.com, cozy-photos.example.com…

**Comment by ArchangeGabriel** [comment]
Just for the record, https://letsencrypt.org/2017/07/06/wildcard-certificates-coming-jan-2018.html

Only DNS challenge planned for now (and whole domain only), which might be an higher complexity to work with, but wildcard nonetheless.
